fix: MethodError in JuliaHub.Experimental.Registries
Fix the method error when calling JuliaHub.Experimental.registries(auth):

ERROR: MethodError: no method matching _parse_registry(::JSON.Object{String, Any})
The function `_parse_registry` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  _parse_registry(::Dict)
   @ JuliaHub ~/JuliaHub/JuliaHub.jl/src/packages.jl:1

Stacktrace:
 [1] _broadcast_getindex_evalf
   @ ./broadcast.jl:699 [inlined]
 [2] _broadcast_getindex
   @ ./broadcast.jl:672 [inlined]
 [3] _getindex
   @ ./broadcast.jl:620 [inlined]
 [4] getindex
   @ ./broadcast.jl:616 [inlined]
 [5] copy
   @ ./broadcast.jl:933 [inlined]
 [6] materialize(bc::Base.Broadcast.Broadcasted{…})
   @ Base.Broadcast ./broadcast.jl:894
 [7] registries(auth::JuliaHub.Authentication)
   @ JuliaHub ~/JuliaHub/JuliaHub.jl/src/packages.jl:24
 [8] top-level scope
   @ ~/JuliaHub/submit-app.jl:7
Some type information was truncated. Use `show(err)` to see complete types.